apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample-app

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: sample-app
  managed-by: argocd

commonAnnotations:
  deployment.kubernetes.io/description: "Sample app deployed via ArgoCD"